name: Deploy Backend to EC2

# push 감지가 불필요한 경우 사용
# 현재 배포 테스트 종료로 push를 감지하지 않도록 하기 위해 사용
on:
  workflow_dispatch:


# 배포 시 master branch push 감지 후 자동 배포
# 배포 단계가 아닐 때는 활성화 금지
#on:
#  push:
#    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # AWS 인증 설정
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # ECR 로그인
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Docker 이미지 빌드 + ECR Push
      - name: Build & Push Docker Image
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          IMAGE_URI="${{ secrets.ECR_REPOSITORY }}:${IMAGE_TAG}"
          
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
          
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      # EC2 SSH 접속 → deploy.sh 실행
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            IMAGE_URI="${{ env.IMAGE_URI }}"
            cd ~/app/scripts
            bash deploy.sh "${IMAGE_URI}"